apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pilot-{{bot_id}}
  namespace: ops-pilot
  {% if enable_ssl %}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  {% endif %}
spec:
  {% if enable_ssl %}
  tls:
    - secretName: pilot-{{bot_id}}-tls
      hosts:
        - {{bot_domain}}
  {% endif %}
  rules:
    - host: {{bot_domain}}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pilot-{{bot_id}}-service
                port:
                  number: 5005