apiVersion: v1
kind: Service
metadata:
  name: pilot-{{bot_id}}-service
spec:
  type: {% if enable_nodeport %}NodePort{% else %}ClusterIP{% endif %}
  selector:
    app: pilot-{{bot_id}}
  ports:
    - name: web
      protocol: TCP
      port: 5005
      targetPort: 5005
      {% if enable_nodeport %}
      nodePort: {{ web_nodeport }}
      {% endif %}
    - name: action
      protocol: TCP
      port: 5055
      targetPort: 5055