# Generated by Django 4.2.7 on 2024-06-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('assistant_id', models.CharField(default='', max_length=255, verbose_name='机器人ID')),
                ('channels', models.ManyToManyField(blank=True, null=True, to='channel_mgmt.channel', verbose_name='通道')),
            ],
            options={
                'verbose_name': '机器人',
                'verbose_name_plural': '机器人',
            },
        ),
        migrations.CreateModel(
            name='BotConversationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_role', models.CharField(choices=[('user', '用户'), ('bot', '机器人')], max_length=255, verbose_name='对话角色')),
                ('conversation', models.TextField(verbose_name='对话内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_mgmt.bot', verbose_name='机器人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel_mgmt.channeluser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话历史',
                'verbose_name_plural': '对话历史',
            },
        ),
    ]
