# Generated by Django 4.2.7 on 2024-06-03 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentpack_mgmt', '0001_initial'),
        ('bot_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='rasa_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.rasamodel', verbose_name='模型'),
        ),
    ]
