# Generated by Django 4.2.7 on 2024-06-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='node_port',
            field=models.IntegerField(default=5005, verbose_name='端口映射'),
        ),
    ]
