# Generated by Django 4.2.7 on 2024-06-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='online',
            field=models.BooleanField(default=False, verbose_name='是否上线'),
        ),
    ]
