# Generated by Django 4.2.7 on 2024-06-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='bot_domain',
            field=models.CharField(default='localhost', max_length=255, verbose_name='域名'),
        ),
        migrations.AddField(
            model_name='bot',
            name='enable_bot_domain',
            field=models.BooleanField(default=False, verbose_name='启用域名'),
        ),
        migrations.AddField(
            model_name='bot',
            name='enable_node_port',
            field=models.BooleanField(default=False, verbose_name='启用端口映射'),
        ),
        migrations.AddField(
            model_name='bot',
            name='node_port',
            field=models.IntegerField(default=5005, verbose_name='端口映射'),
        ),
    ]
