# Generated by Django 4.2.7 on 2024-08-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='node_selector',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='节点选择'),
        ),
    ]
