# Generated by Django 4.2.7 on 2024-07-05 13:17

import apps.core.encoders
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_mgmt', '0003_remove_botskillrule_prompt_remove_botskillrule_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('integration_type', models.CharField(choices=[('salt', 'SALT'), ('weops', 'WeOPS'), ('jenkins', 'Jenkins')], max_length=255, verbose_name='类型')),
                ('config', models.JSONField(default=dict, encoder=apps.core.encoders.PrettyJSONEncoder, null=True, verbose_name='配置')),
                ('bot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_mgmt.bot', verbose_name='机器人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '集成',
                'verbose_name_plural': '集成',
            },
        ),
    ]
