# Generated by Django 4.2.7 on 2024-05-29 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel_mgmt', '0001_initial'),
        ('contentpack_mgmt', '0002_initial'),
        ('bot_mgmt', '0003_remove_bot_channels_alter_bot_rasa_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='channels',
        ),
        migrations.AlterField(
            model_name='bot',
            name='rasa_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentpack_mgmt.rasamodel', verbose_name='模型'),
        ),
        migrations.AddField(
            model_name='bot',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, to='channel_mgmt.channel', verbose_name='通道'),
        ),
    ]
