# Generated by Django 4.2.7 on 2024-07-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0004_integrations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integrations',
        ),
    ]
