# Generated by Django 4.2.7 on 2024-07-13 14:00

import apps.core.mixinx
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_mgmt', '0005_delete_integrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('skill_id', models.CharField(max_length=100, unique=True, verbose_name='技能ID')),
                ('skill_type', models.CharField(choices=[('salt_stack', 'SaltStack')], max_length=100, verbose_name='类型')),
                ('skill_config', django_yaml_field.fields.YAMLField(blank=True, null=True, verbose_name='技能配置')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '维护者相关字段',
                'abstract': False,
            },
            bases=(models.Model, apps.core.mixinx.EncryptableMixin),
        ),
    ]
