# Generated by Django 4.2.7 on 2024-07-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0006_automationskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='automation_skills',
            field=models.ManyToManyField(blank=True, to='bot_mgmt.automationskill', verbose_name='自动化技能'),
        ),
    ]
