# Generated by Django 4.2.7 on 2024-07-14 13:58

import apps.core.mixinx
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_mgmt', '0007_bot_automation_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('integration', models.CharField(choices=[('jenkins', 'Jenkins')], max_length=100, verbose_name='集成')),
                ('integration_config', django_yaml_field.fields.YAMLField(blank=True, null=True, verbose_name='集成配置')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '维护者相关字段',
                'abstract': False,
            },
            bases=(models.Model, apps.core.mixinx.EncryptableMixin),
        ),
        migrations.AddField(
            model_name='automationskill',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_mgmt.integration', verbose_name='集成'),
        ),
    ]
