# Generated by Django 4.2.7 on 2024-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0008_integration_automationskill_integration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='automation_skills',
        ),
        migrations.AddField(
            model_name='bot',
            name='integration',
            field=models.ManyToManyField(blank=True, to='bot_mgmt.integration', verbose_name='集成'),
        ),
    ]
