# Generated by Django 4.2.7 on 2024-07-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_mgmt', '0009_remove_bot_automation_skills_bot_integration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationskill',
            options={'verbose_name': '自动化技能', 'verbose_name_plural': '自动化技能'},
        ),
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': '集成', 'verbose_name_plural': '集成'},
        ),
    ]
