# Generated by Django 4.2.7 on 2024-05-28 07:38

import apps.core.encoders
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('embed_model', models.CharField(choices=[('fastembed', 'FastEmbed')], max_length=255, verbose_name='嵌入模型')),
                ('embed_config', models.JSONField(blank=True, default=dict, encoder=apps.core.encoders.PrettyJSONEncoder, null=True, verbose_name='嵌入配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'Embed模型',
                'verbose_name_plural': 'Embed模型',
            },
        ),
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('llm_model', models.CharField(choices=[('gpt-3.5-turbo-16k', 'GPT-3.5 Turbo 16K')], max_length=255, verbose_name='LLM模型')),
                ('llm_config', models.JSONField(blank=True, default=dict, encoder=apps.core.encoders.PrettyJSONEncoder, null=True, verbose_name='LLM配置')),
            ],
            options={
                'verbose_name': 'LLM模型',
                'verbose_name_plural': 'LLM模型',
            },
        ),
        migrations.CreateModel(
            name='LLMSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('skill_prompt', models.TextField(blank=True, null=True, verbose_name='技能提示词')),
                ('enable_conversation_history', models.BooleanField(default=False, verbose_name='启用对话历史')),
                ('conversation_window_size', models.IntegerField(default=10, verbose_name='对话窗口大小')),
                ('enable_rag', models.BooleanField(default=False, verbose_name='启用RAG')),
                ('rag_top_k', models.IntegerField(default=5, verbose_name='RAG返回结果数量')),
                ('rag_num_candidates', models.IntegerField(default=1000, verbose_name='RAG向量候选数量')),
                ('knowledge_base_folders', models.ManyToManyField(blank=True, null=True, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识库')),
                ('llm_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.llmmodel', verbose_name='LLM模型')),
            ],
            options={
                'verbose_name': 'LLM技能管理',
                'verbose_name_plural': 'LLM技能管理',
            },
        ),
    ]
