# Generated by Django 4.2.7 on 2024-06-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmskill',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AddConstraint(
            model_name='llmskill',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_name'),
        ),
    ]
