# Generated by Django 4.2.7 on 2024-06-06 05:41

import apps.core.encoders
import apps.core.mixinx
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RerankProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('rerank_model', models.CharField(choices=[('bce', 'BCE')], max_length=255, verbose_name='Rerank模型')),
                ('rerank_config', models.JSONField(blank=True, default=dict, encoder=apps.core.encoders.PrettyJSONEncoder, null=True, verbose_name='Rerank配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'Rerank模型',
                'verbose_name_plural': 'Rerank模型',
            },
            bases=(models.Model, apps.core.mixinx.EncryptableMixin),
        ),
        migrations.AddField(
            model_name='llmskill',
            name='enable_rerank',
            field=models.BooleanField(default=False, verbose_name='启用Rerank'),
        ),
        migrations.AddField(
            model_name='llmskill',
            name='rerank_top_k',
            field=models.IntegerField(default=5, verbose_name='Rerank返回结果数量'),
        ),
        migrations.AlterField(
            model_name='embedprovider',
            name='embed_model',
            field=models.CharField(choices=[('fastembed', 'FastEmbed'), ('openai', 'OpenAI'), ('bceembedding', 'BCEEmbedding')], max_length=255, verbose_name='嵌入模型'),
        ),
        migrations.AddField(
            model_name='llmskill',
            name='rerank_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.rerankprovider', verbose_name='Rerank模型'),
        ),
    ]
