# Generated by Django 4.2.7 on 2024-06-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_provider_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="skill_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="技能ID"),
        ),
    ]
