# Generated by Django 4.2.7 on 2024-06-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0002_rerankprovider_llmskill_enable_rerank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmskill',
            name='rag_num_candidates',
        ),
        migrations.RemoveField(
            model_name='llmskill',
            name='rag_top_k',
        ),
    ]
