# Generated by Django 4.2.7 on 2024-07-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0002_alter_embedprovider_embed_model_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('ocr_config', models.JSONField(blank=True, default=dict, null=True, verbose_name='OCR配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'OCR模型',
                'verbose_name_plural': 'OCR模型',
            },
        ),
    ]
