# Generated by Django 4.2.7 on 2024-07-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0003_ocrprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='llm_model_type',
            field=models.CharField(choices=[('chat-gpt', 'ChatGPT'), ('zhipu', '智谱AI')], max_length=255, verbose_name='LLM模型类型'),
        ),
    ]
