# Generated by Django 4.2.7 on 2024-06-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0003_llmskill_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmmodel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='llmskill',
            name='skill_id',
            field=models.CharField(blank=True, choices=[('action_llm_fallback', '开放领域问答')], max_length=255, null=True, verbose_name='技能ID'),
        ),
    ]
