# Generated by Django 4.2.7 on 2024-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0005_alter_llmmodel_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
    ]
