# Generated by Django 4.2.7 on 2024-06-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0006_alter_llmmodel_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmskill',
            name='skill_id',
            field=models.CharField(blank=True, choices=[('action_llm_fallback', '开放领域问答')], max_length=255, null=True, verbose_name='技能类型'),
        ),
    ]
