# Generated by Django 4.2.7 on 2024-06-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0008_alter_llmskill_skill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmskill',
            name='rag_score_threshold',
            field=models.FloatField(default=0.7, verbose_name='RAG分数阈值'),
        ),
    ]
