# Generated by Django 4.2.7 on 2024-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0009_llmskill_rag_score_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmskill',
            name='enable_rag_knowledge_source',
            field=models.BooleanField(default=False, verbose_name='显示RAG知识来源'),
        ),
    ]
