from .bot_actions import BotActionsAdmin
from .rasa_entity import RasaEntityAdmin
from .intent import IntentAdmin
from .intent_corpus import IntentCorpusAdmin
from .rasa_rules import RasaRulesAdmin
from .rasa_stories import RasaStoriesAdmin
from .rasa_response import RasaResponseAdmin
from .rasa_response_corpus import RasaResponseCorpusAdmin
from .rasa_forms import RasaFormsAdmin
from .rasa_model import RasaModelAdmin
from .content_pack import ContentPackAdmin
from .rasa_slots import RasaSlotsAdmin
