recipe: default.v1
assistant_id: ops-pilot
language: zh

pipeline:

  - name: KeywordIntentClassifier
    case_sensitive: True

  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1



policies:

  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_llm_fallback"