import os

CONVERSATION_MQ_HOST = os.getenv("CONVERSATION_MQ_HOST", "localhost")
CONVERSATION_MQ_PORT = int(os.getenv("CONVERSATION_MQ_PORT", 5672))
CONVERSATION_MQ_USER = os.getenv("CONVERSATION_MQ_USER", "admin")
CONVERSATION_MQ_PASSWORD = os.getenv("CONVERSATION_MQ_PASSWORD", "password")
