version: '3.3'
services:

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
      POSTGRES_DB: ops-pilot
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres:
