apiVersion: v1
kind: ConfigMap
metadata:
  name: munchkin-config
  namespace: ops-pilot
data:
  SECRET_KEY: acheig2fo6Xai7Eighei1jei1maigahr
  DEBUG: "False"

  DB_NAME: munchkin
  DB_USER: postgres
  DB_PASSWORD: "password"
  DB_HOST: postgres
  DB_PORT: "5432"

  REDIS_CACHE_URL: ""
  CSRF_TRUSTED_ORIGINS: "http://munchkin.ops-pilot.cc"
  ENABLE_CELERY: "True"
  CELERY_BROKER_URL: amqp://admin:password@rabbitmq-service:5672//
  CELERY_RESULT_BACKEND: db+postgresql://postgres:password@postgres/munchkin

  MINIO_ENDPOINT: minio:9000
  MINIO_ACCESS_KEY: minio
  MINIO_SECRET_KEY: minio_password

  ELASTICSEARCH_URL: http://elasticsearch:9200
  ELASTICSEARCH_PASSWORD: ud3Oop9Aepah

  CONVERSATION_MQ_HOST: rabbitmq-service
  CONVERSATION_MQ_PORT: "5672"
  CONVERSATION_MQ_USER: admin
  CONVERSATION_MQ_PASSWORD: password

  MUNCHKIN_BASE_URL: http://munchkin.ops-pilot:8000