# Generated by Django 4.2.7 on 2024-06-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("model_provider_mgmt", "0001_initial"),
        ("contentpack_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botactions",
            name="llm_skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="model_provider_mgmt.llmskill",
                verbose_name="大模型技能",
            ),
        ),
    ]
