# Generated by Django 4.2.7 on 2024-06-18 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model_provider_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='embed_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='rerank_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.rerankprovider', verbose_name='Rerank模型'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='knowledge_base_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
