# Generated by Django 4.2.7 on 2024-07-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0002_alter_embedprovider_embed_model_type'),
        ('knowledge_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='enable_general_parse',
        ),
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='enable_semantic_chunck_parse',
        ),
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='general_parse_chunk_overlap',
        ),
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='general_parse_chunk_size',
        ),
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='semantic_chunk_parse_embedding_model',
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='enable_general_parse',
            field=models.BooleanField(default=True, verbose_name='分块解析'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='enable_semantic_chunck_parse',
            field=models.BooleanField(default=False, verbose_name='语义分块解析'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='general_parse_chunk_overlap',
            field=models.IntegerField(default=32, verbose_name='分块重叠'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='general_parse_chunk_size',
            field=models.IntegerField(default=256, verbose_name='分块大小'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
        migrations.AddField(
            model_name='manualknowledge',
            name='enable_general_parse',
            field=models.BooleanField(default=True, verbose_name='分块解析'),
        ),
        migrations.AddField(
            model_name='manualknowledge',
            name='enable_semantic_chunck_parse',
            field=models.BooleanField(default=False, verbose_name='语义分块解析'),
        ),
        migrations.AddField(
            model_name='manualknowledge',
            name='general_parse_chunk_overlap',
            field=models.IntegerField(default=32, verbose_name='分块重叠'),
        ),
        migrations.AddField(
            model_name='manualknowledge',
            name='general_parse_chunk_size',
            field=models.IntegerField(default=256, verbose_name='分块大小'),
        ),
        migrations.AddField(
            model_name='manualknowledge',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
        migrations.AddField(
            model_name='webpageknowledge',
            name='enable_general_parse',
            field=models.BooleanField(default=True, verbose_name='分块解析'),
        ),
        migrations.AddField(
            model_name='webpageknowledge',
            name='enable_semantic_chunck_parse',
            field=models.BooleanField(default=False, verbose_name='语义分块解析'),
        ),
        migrations.AddField(
            model_name='webpageknowledge',
            name='general_parse_chunk_overlap',
            field=models.IntegerField(default=32, verbose_name='分块重叠'),
        ),
        migrations.AddField(
            model_name='webpageknowledge',
            name='general_parse_chunk_size',
            field=models.IntegerField(default=256, verbose_name='分块大小'),
        ),
        migrations.AddField(
            model_name='webpageknowledge',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
    ]
