# Generated by Django 4.2.7 on 2024-06-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0002_alter_llmskill_name_llmskill_unique_owner_name'),
        ('knowledge_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='enable_semantic_chunck_parse',
            field=models.BooleanField(default=False, verbose_name='语义分块解析'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
    ]
