# Generated by Django 4.2.7 on 2024-06-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_mgmt", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasefolder",
            name="general_parse_chunk_overlap",
            field=models.IntegerField(default=32, verbose_name="分块重叠"),
        ),
        migrations.AlterField(
            model_name="knowledgebasefolder",
            name="general_parse_chunk_size",
            field=models.IntegerField(default=256, verbose_name="分块大小"),
        ),
        migrations.AlterField(
            model_name="knowledgebasefolder",
            name="rag_k",
            field=models.IntegerField(default=50, verbose_name="返回结果数量"),
        ),
        migrations.AlterField(
            model_name="knowledgebasefolder",
            name="rerank_top_k",
            field=models.IntegerField(default=10, verbose_name="Rerank返回结果数量"),
        ),
    ]
