# Generated by Django 4.2.7 on 2024-06-06 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0004_remove_llmskill_enable_rerank_and_more'),
        ('knowledge_mgmt', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='enable_rerank',
            field=models.BooleanField(default=False, verbose_name='启用Rerank'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='rerank_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.rerankprovider', verbose_name='Rerank模型'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='rerank_top_k',
            field=models.IntegerField(default=5, verbose_name='Rerank返回结果数量'),
        ),
    ]
