# Generated by Django 4.2.7 on 2024-06-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge_mgmt",
            "0003_alter_knowledgebasefolder_general_parse_chunk_overlap_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualKnowledge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "knowledge_base_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="knowledge_mgmt.knowledgebasefolder",
                        verbose_name="知识",
                    ),
                ),
            ],
            options={
                "verbose_name": "手工录入",
                "verbose_name_plural": "手工录入",
            },
        ),
    ]
