# Generated by Django 4.2.7 on 2024-07-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0003_remove_knowledgebasefolder_enable_general_parse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileknowledge',
            name='excel_full_content_parse',
            field=models.BooleanField(default=False, verbose_name='Excel全内容解析'),
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='excel_header_row_parse',
            field=models.BooleanField(default=False, verbose_name='Excel表头+行组合解析'),
        ),
    ]
