# Generated by Django 4.2.7 on 2024-05-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0003_knowledgebasefolder_text_search_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasefolder',
            name='text_search_weight',
            field=models.FloatField(default=0.9, verbose_name='文本检索权重'),
        ),
        migrations.AlterField(
            model_name='knowledgebasefolder',
            name='vector_search_weight',
            field=models.FloatField(default=0.1, verbose_name='向量检索权重'),
        ),
    ]
