# Generated by Django 4.2.7 on 2024-06-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0003_knowledgebasefolder_enable_rerank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='enable_qa_generation',
            field=models.BooleanField(default=True, verbose_name='问答生成'),
        ),
    ]
