# Generated by Django 4.2.7 on 2024-06-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0004_remove_llmskill_enable_rerank_and_more'),
        ('knowledge_mgmt', '0004_knowledgebasefolder_enable_qa_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='qa_generation_llm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model_provider_mgmt.llmmodel', verbose_name='LLM模型'),
        ),
    ]
