# Generated by Django 4.2.7 on 2024-05-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0004_alter_knowledgebasefolder_text_search_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='train_progress',
            field=models.FloatField(default=0, verbose_name='训练进度'),
        ),
    ]
