# Generated by Django 4.2.7 on 2024-06-08 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0004_manualknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPageKnowledge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('url', models.URLField(verbose_name='URL')),
                ('knowledge_base_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgebasefolder', verbose_name='知识')),
            ],
            options={
                'verbose_name': '网页知识',
                'verbose_name_plural': '网页知识',
            },
        ),
    ]
