# Generated by Django 4.2.7 on 2024-07-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0004_fileknowledge_excel_full_content_parse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileknowledge',
            name='excel_full_content_parse',
            field=models.BooleanField(default=True, verbose_name='Excel全内容解析'),
        ),
    ]
