# Generated by Django 4.2.7 on 2024-05-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0005_knowledgebasefolder_train_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebasefolder',
            name='enable_general_parse',
        ),
    ]
