# Generated by Django 4.2.7 on 2024-07-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0003_ocrprovider'),
        ('knowledge_mgmt', '0005_alter_fileknowledge_excel_full_content_parse'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='ocr_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_ocr_model', to='model_provider_mgmt.ocrprovider', verbose_name='OCR模型'),
        ),
    ]
