# Generated by Django 4.2.7 on 2024-05-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0006_remove_knowledgebasefolder_enable_general_parse'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='enable_general_parse',
            field=models.BooleanField(default=True, verbose_name='分块解析'),
        ),
    ]
