# Generated by Django 4.2.7 on 2024-06-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0006_fileknowledge_custom_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileknowledge',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义元数据'),
        ),
        migrations.AlterField(
            model_name='manualknowledge',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义元数据'),
        ),
        migrations.AlterField(
            model_name='webpageknowledge',
            name='custom_metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='自定义元数据'),
        ),
    ]
