# Generated by Django 4.2.7 on 2024-07-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0004_alter_llmmodel_llm_model_type'),
        ('knowledge_mgmt', '0008_alter_fileknowledge_semantic_chunk_parse_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileknowledge',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
    ]
