# Generated by Django 4.2.7 on 2024-06-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "knowledge_mgmt",
            "0008_fileknowledge_created_at_fileknowledge_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileknowledge",
            old_name="created_by",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="manualknowledge",
            old_name="created_by",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="webpageknowledge",
            old_name="created_by",
            new_name="owner",
        ),
        migrations.RemoveField(
            model_name="fileknowledge",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="manualknowledge",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="webpageknowledge",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="fileknowledge",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="manualknowledge",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="webpageknowledge",
            name="updated_at",
        ),
    ]
