# Generated by Django 4.2.7 on 2024-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_mgmt', '0009_alter_fileknowledge_semantic_chunk_parse_embedding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileknowledge',
            name='enable_ocr_parse',
            field=models.BooleanField(default=False, verbose_name='启用OCR解析'),
        ),
    ]
