# Generated by Django 4.2.7 on 2024-07-18 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model_provider_mgmt', '0004_alter_llmmodel_llm_model_type'),
        ('knowledge_mgmt', '0010_fileknowledge_enable_ocr_parse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualknowledge',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
        migrations.AlterField(
            model_name='webpageknowledge',
            name='semantic_chunk_parse_embedding_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_chunk_parse_embedding_model', to='model_provider_mgmt.embedprovider', verbose_name='嵌入模型'),
        ),
    ]
