# Generated by Django 4.2.7 on 2024-07-22 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_yaml_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge_mgmt', '0011_alter_manualknowledge_semantic_chunk_parse_embedding_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeIntegration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='集成名称')),
                ('integration_config', django_yaml_field.fields.YAMLField(blank=True, null=True, verbose_name='集成配置')),
                ('integration', models.CharField(choices=[('weops', 'WeOps'), ('playwright', 'Playwright'), ('simple_web_scrapy', '网站爬虫')], max_length=100, verbose_name='集成')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '知识集成',
                'verbose_name_plural': '知识集成',
            },
        ),
        migrations.AddField(
            model_name='fileknowledge',
            name='knowledge_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgeintegration', verbose_name='知识集成'),
        ),
        migrations.AddField(
            model_name='knowledgebasefolder',
            name='knowledge_integration',
            field=models.ManyToManyField(blank=True, related_name='knowledge_base_folders', to='knowledge_mgmt.knowledgeintegration', verbose_name='知识集成'),
        ),
        migrations.AddField(
            model_name='manualknowledge',
            name='knowledge_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgeintegration', verbose_name='知识集成'),
        ),
        migrations.AddField(
            model_name='webpageknowledge',
            name='knowledge_integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_mgmt.knowledgeintegration', verbose_name='知识集成'),
        ),
    ]
