# Generated by Django 4.2.7 on 2024-04-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='意图名称')),
                ('description', models.TextField(verbose_name='意图描述')),
            ],
            options={
                'verbose_name': '意图',
                'verbose_name_plural': '意图',
            },
        ),
        migrations.CreateModel(
            name='IntentCorpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corpus', models.TextField(verbose_name='语料')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops_pilot.intent', verbose_name='意图')),
            ],
            options={
                'verbose_name': '意图语料',
                'verbose_name_plural': '意图语料',
            },
        ),
    ]
