# Generated by Django 4.2.7 on 2024-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0002_intent_intentcorpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='意图描述'),
        ),
    ]
