# Generated by Django 4.2.7 on 2024-04-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0004_alter_intentcorpus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='动作名称')),
                ('action_func', models.CharField(max_length=255, verbose_name='动作函数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='动作描述')),
            ],
            options={
                'verbose_name': '动作',
                'verbose_name_plural': '动作',
            },
        ),
    ]
