# Generated by Django 4.2.7 on 2024-04-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0005_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='实体名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='实体描述')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
            },
        ),
    ]
