# Generated by Django 4.2.7 on 2024-04-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0006_entities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='槽位名称')),
                ('slot_type', models.CharField(max_length=255, verbose_name='槽位类型')),
                ('influence_conversation', models.BooleanField(default=False, verbose_name='是否影响对话')),
                ('slot_mappings', models.TextField(blank=True, null=True, verbose_name='槽位映射')),
                ('description', models.TextField(blank=True, null=True, verbose_name='槽位描述')),
            ],
            options={
                'verbose_name': '槽位',
                'verbose_name_plural': '槽位',
            },
        ),
    ]
