# Generated by Django 4.2.7 on 2024-04-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0008_remove_slots_slot_mappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='表单名称')),
                ('slots', models.ManyToManyField(to='ops_pilot.slots', verbose_name='槽位')),
            ],
            options={
                'verbose_name': '表单',
                'verbose_name_plural': '表单',
            },
        ),
    ]
