# Generated by Django 4.2.7 on 2024-04-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0009_slotform'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotform',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
