# Generated by Django 4.2.7 on 2024-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0012_rules_rules_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='rules_condition',
            field=models.TextField(blank=True, null=True, verbose_name='规则条件'),
        ),
    ]
