# Generated by Django 4.2.7 on 2024-04-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0013_rules_rules_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCorpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='回复')),
                ('channel', models.CharField(max_length=255, verbose_name='渠道')),
                ('buttons', models.TextField(blank=True, null=True, verbose_name='按钮')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='回复名称')),
                ('response_corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops_pilot.responsecorpus', verbose_name='回复语料')),
            ],
            options={
                'verbose_name': '回复',
                'verbose_name_plural': '回复',
            },
        ),
    ]
