# Generated by Django 4.2.7 on 2024-04-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0014_responsecorpus_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='response_corpus',
        ),
        migrations.AddField(
            model_name='responsecorpus',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ops_pilot.responses', verbose_name='回复'),
        ),
    ]
