# Generated by Django 4.2.7 on 2024-04-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0015_remove_responses_response_corpus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsecorpus',
            options={'verbose_name': '回复语料', 'verbose_name_plural': '回复语料'},
        ),
    ]
