# Generated by Django 4.2.7 on 2024-04-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0016_alter_responsecorpus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecorpus',
            name='channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='渠道'),
        ),
    ]
