# Generated by Django 4.2.7 on 2024-04-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0017_alter_responsecorpus_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='故事名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('story_steps', models.TextField(blank=True, null=True, verbose_name='故事步骤')),
            ],
            options={
                'verbose_name': '故事',
                'verbose_name_plural': '故事',
            },
        ),
    ]
