# Generated by Django 4.2.7 on 2024-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0018_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='bots',
            field=models.ManyToManyField(to='ops_pilot.bot', verbose_name='机器人'),
        ),
        migrations.AddField(
            model_name='stories',
            name='bots',
            field=models.ManyToManyField(to='ops_pilot.bot', verbose_name='机器人'),
        ),
    ]
