# Generated by Django 4.2.7 on 2024-04-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0019_rules_bots_stories_bots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='bots',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='bots',
        ),
    ]
