# Generated by Django 4.2.7 on 2024-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops_pilot', '0020_remove_rules_bots_remove_stories_bots'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='rules',
            field=models.ManyToManyField(blank=True, to='ops_pilot.rules', verbose_name='规则'),
        ),
        migrations.AddField(
            model_name='bot',
            name='stories',
            field=models.ManyToManyField(blank=True, to='ops_pilot.stories', verbose_name='故事'),
        ),
    ]
