FROM ubuntu:22.04

RUN apt-get update 
RUN apt-get install -y libhdf5-dev iftop  net-tools iputils-ping  vim
RUN apt-get install -y python3 python3-pip build-essential
RUN apt-get install unzip wget curl -y
RUN apt-get install pkg-config libssl-dev libffi-dev -y
RUN apt-get install -y supervisor

RUN pip install pip-tools 
ADD ./models/nltk_data /root/nltk_data

