apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: ops-pilot-dev
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.12.1
          env:
            - name: discovery.type
              value: "single-node"
            - name: bootstrap.memory_lock
              value: "false"
            - name: xpack.security.enabled
              value: "true"
            - name: ELASTIC_PASSWORD
              value: "ud3Oop9Aepah"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: TZ
              value: "Asia/Shanghai"
          ports:
            - containerPort: 9200
          resources:
            limits:
              memory: "1Gi"
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: ops-pilot-dev
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200