apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:10.2.2
          ports:
            - containerPort: 3000
          env:
            - name: GF_DATABASE_TYPE
              value: "postgres"
            - name: GF_DATABASE_HOST
              value: "postgres"
            - name: GF_DATABASE_NAME
              value: "grafana"            
            - name: GF_DATABASE_USER
              value: "postgres"
            - name: GF_DATABASE_PASSWORD
              value: "password"
            - name: GF_DATABASE_MAX_OPEN_CONN
              value: "300"       
            - name: GF_PATHS_DATA
              value: "/var/lib/grafana"
            - name: GF_PATHS_LOGS
              value: "/var/log/grafana"
            - name: GF_PATHS_PLUGINS
              value: "/var/lib/grafana/plugins"            
            - name: GF_FEATURE_TOGGLES_ENABLE
              value: "flameGraph"

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus-stack
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
