apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: prometheus-stack
data:
  local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/scratch
      # alertmanager_url: http://alertmanager:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true

    ingester:
      wal:
        enabled: true
        dir: /loki/wal
      lifecycler:
        address: 0.0.0.0
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
      max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
      chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
      chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
      max_transfer_retries: 0     # Chunk transfers disabled

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h        
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    compactor:
      working_directory: /loki/boltdb-shipper-compactor
      shared_store: filesystem

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 360h
      max_query_series: 10000000
      max_query_parallelism: 100
      ingestion_rate_strategy: local
      ingestion_rate_mb: 1500
      ingestion_burst_size_mb: 2000

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

    querier:
      max_concurrent: 2048

    frontend:
      max_outstanding_per_tenant: 4096
      compress_responses: true

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    query_scheduler:
      max_outstanding_requests_per_tenant: 10000  

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: prometheus-stack
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.1
          args:
            - '-config.file=/etc/loki/local-config.yaml'
            - '-config.expand-env=true'
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-local-config
              mountPath: /etc/loki
              readOnly: true
            - name: loki-storage
              mountPath: /loki
            - name: loki-localtime
              mountPath: /etc/localtime
              readOnly: true        
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: zh_CN.UTF-8
      volumes:
        - name: loki-local-config
          configMap:
            name: loki-config
        - name: loki-localtime
          hostPath:
            path: /etc/localtime
  volumeClaimTemplates:
    - metadata:
        name: loki-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: prometheus-stack
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      name: http
      port: 3100
      targetPort: 3100